### ISSUE TITLE
Installation for non-node users

### ISSUE THREAD

**Issue by J7mbo** [marionebl/jogwheel#106]
Some people don't use Node, or grunt etc - and they just want to use this client-side JS library. It would be incredibly useful to provide basic instructions for people to install and use the library in a basic application without any other dependencies (which file should be included... index.js? etc).

**Comment by marionebl** [comment]
Hey @J7mbo,

Thanks for the heads up! Currently usage of jogwheel involves a JS bundler such as browserify, webpack or rollup. Making usage easier could be done by:

* Pushing unminified and minified releases to a CDN
* Attaching builds to Github releases
* Updating the docs accordingly 

ETA for this is end of next week, stay tuned. 

In the meantime you can give jogwheel a ride via [brcdn](https://www.brcdn.org/?module=jogwheel&version=1.1.0)

**Comment by marionebl** [comment]
A basic example of brcdn and general usage can be found here: http://codepen.io/marionebl/pen/rOEOZZ?editors=110

**Comment by marionebl** [comment]
Enhanced the usage section to discuss usage of ready made bundles from brcdn.org, should be sufficient for alternate use cases - comment if you run into problems
