### ISSUE TITLE
First part animation is being played at wrong speed

### ISSUE THREAD

**Issue by J7mbo** [marionebl/jogwheel#161]
The first part of an animation is being played too slowly. Here's a [codepen](http://codepen.io/anon/pen/YwKbQZ). If you remove the Jogwheel JS and then let the animation play, it plays at the correct speed, but when you add Jogwheel it slows the animation down (might be a little hard to see but it's there).

**Comment by nordisk** [comment]
Hi @marionebl. 
I can confirm that. Here is another [codepen](http://codepen.io/nordisk/pen/RrbmML) showing this in a slightly better way.

The reason, from my observations, is that JogWheel is not treating the interpolation between the keyframes correctly, eg. it seems like it is always using a linear interpolation regardless the set  `animation-timing-function`.

**Comment by marionebl** [comment]
Hey, thanks for the test cases. I'll have a look at it tomorrow, stay tuned!

**Comment by nordisk** [comment]
Thanks @marionebl !

**Comment by marionebl** [comment]
Reference for this should be http://www.w3.org/TR/web-animations/#the-animationeffecttimingreadonly-interface

**Comment by marionebl** [comment]
Ok so apparently this is a problem with timing-inputs not supported in `web-aniamtions-js`. See the feature matrix as per https://github.com/web-animations/web-animations-js#build-target-comparison. Unfortunately this is not in scope for jogwheel, you could file an issue at https://github.com/web-animations/web-animations-next/issues instead.

**Comment by J7mbo** [comment]
Thanks for looking into that @marionebl. Could you recommend an alternative polyfil that you know of that supports this?

**Comment by marionebl** [comment]
Nothing I am aware of, sorry.
