### ISSUE TITLE
Jogwheel can't control filters

### ISSUE THREAD

**Issue by J7mbo** [marionebl/jogwheel#162]
Jogwheel can't control filters. I've tried `-webkit-filter: sepia` and `-webkit-filter: blur`. It's not showing or tweening them.

**Comment by marionebl** [comment]
Probably this also a problem with `web-animations-js`, possibly even with the current `element.animate` implementation in Blink. Pending further investigation.

**Comment by marionebl** [comment]
According to this codepen http://codepen.io/marionebl/pen/RrbzOO event the current `web-animations` implementation in Blink does not support 'filter'. Documentation changes are pending, closing this for now.
