### ISSUE TITLE
Exposes object in example is "JogWheel", but just can find "jogwheel" in window

### ISSUE THREAD

**Issue by meandmax** [marionebl/jogwheel#167]
Im not sure if you want to expose jogwheel or JogWheel to the window object. Currently also an issue why the example is not working...

![bildschirmfoto 2015-12-04 um 10 23 40](https://cloud.githubusercontent.com/assets/6309638/11586138/3f670368-9a71-11e5-9c4a-e0b87b724cce.png)

**Comment by marionebl** [comment]
Actually this is controlled via the `standalone`-Parameter at brcdn. Fixed the example. Thanks for the heads-up! :fist:
