### ISSUE TITLE
Can we remove Jogwheel after applying it?

### ISSUE THREAD

**Issue by J7mbo** [marionebl/jogwheel#170]
When we create an instance of Jogwheel, it takes over the animations for us. Can we call some sort of method to release control from Jogwheel and return everything to it's previous state? My goal is to use Jogwheel to skip to a specific part of an animation, pause, then remove Jogwheel, and the animation is still paused via `animation-play-state` but untouched otherwise.

Perhaps some sort of `::release()` method?

**Comment by marionebl** [comment]
Hey @J7mbo, this is planned for a future release via `JogWheel.prototype.unplug`. I'll have to roll around the ins-and-outs of leaving over styles on unplugged elements, there are a lot of possible behaviors and connected edge cases

**Comment by J7mbo** [comment]
Hey @marionebl, calling `unplug` call be reversible as well? So we should be able to re-apply jogwheel at a later time and continue using it? I'm still trying to come up with ways around not being able to animate filters and potentially removing jogwheel then re-adding it after a given filter might be a (**hacky**) way forward.

**Comment by marionebl** [comment]
This would be provided by `plug` then. Stay tuned. :fist:

**Comment by marionebl** [comment]
Hey @J7mbo, this should do the trick, right?: http://codepen.io/marionebl/pen/eJWweq
