### ISSUE TITLE
onFinish handlers

### ISSUE THREAD

**Issue by J7mbo** [marionebl/jogwheel#182]
Hey, how can I be alerted that a given animation has finished?

I've been looking through the code and I've seen multiple references to 'finished' members. There's the `_finishHandlers` private member and there's the `onfinish` player member, (which I believe was replaced with `finished` according to the W3 spec?). I've also tried observe-js and couldn't get that working, but clearly that's a hack, and using a `setInterval` call to watch for the `_isFinished` flag changing doesn't help.

Appending both promises and anonymous functions to these don't yield the result I'm after, and there's nothing I can find in the documentation.

What's the **correct** method for adding a callback handler to an animation?

**Comment by marionebl** [comment]
Hey, 

according to my tests this works as expected: http://codepen.io/marionebl/pen/Bjyjvz
Keep in mind that `finish` only fires for `Animation` when `iterationCount !== Infinity`.

**Comment by J7mbo** [comment]
Ah yep, apologies - I presumed this was a Jogwheel specific object and not a generic one :-)
