### ISSUE TITLE
BRCDN.org fails to serve files for example

### ISSUE THREAD

**Issue by Ticolyle** [marionebl/jogwheel#422]
Hi everyone. Love the library but I ran into an issue when trying to run the example fast-track demo. 

brcdn.org seems to have a build error for the hosted file so the demo is unable to run. For example this url from the demo:
`https://www.brcdn.org/jogwheel/1.4.3/?standalone=jogwheel&uglify=true` 
It seems to be hanging on the uglify script. 

Fails to load and instead produces this error on brcdn:
```
Error: Build Error 1: time="2016-04-29T14:06:33-04:00" level="fatal" msg="Error response from daemon: Cannot start container 172d89b32345ceab48aa8cc8dd13eeef5c646aa18797e20a9c7295b4bc2da458: fork/exec /var/lib/docker/init/dockerinit-1.5.0: cannot allocate memory" 
(while building jogwheel@1.4.3)
   at /root/instances/www.brcdn.org/blue/lib/build.js:116:13
   at /root/instances/www.brcdn.org/blue/node_modules/promise/lib/core.js:33:15
   at flush (/root/instances/www.brcdn.org/blue/node_modules/promise/node_modules/asap/asap.js:27:13)
   at process._tickCallback (node.js:442:13)
```

Also, the web-animations-js libarary does not seem to be available on brcdn.org at all.

**Comment by marionebl** [comment]
Thanks for the heads-up; I'll have a look at this when I am back from a trip without proper working machine, expect this to be resolved around next week.

**Comment by marionebl** [comment]
https://github.com/ForbesLindesay/brcdn.org/issues/12
