### ISSUE TITLE
Properly handle iteration count

### ISSUE THREAD

**Issue by KingHenne** [marionebl/jogwheel#76]
If I’m not mistaken, https://github.com/marionebl/jogwheel/blob/master/source/library/get-player.js#L35 should be changed to:
```js
[prefix('animationIterationCount')]: iterationCount,
```

which must be mapped to `iterations`:
```js
const iterations = iterationCount === 'infinite' ? Infinity : iterationCount;
```

**Comment by marionebl** [comment]
Thanks for the heads up, will fix this with the next release! :fist:

**Comment by KingHenne** [comment]
Also, change https://github.com/marionebl/jogwheel/blob/master/source/library/get-player.js#L36 to:

```js
[prefix('animationTimingFunction')]: easing,
```

**Comment by marionebl** [comment]
Should be fixed with `v0.1.3`, please review and close if fixed

**Comment by KingHenne** [comment]
Almost. Is it intended that [`getAnimationIterations()`](https://github.com/marionebl/jogwheel/blob/master/source/library/get-player.js#L24) does not handle `'infinite'` (as suggested above)? In this case the animation property `iterations` becomes `NaN`.

**Comment by marionebl** [comment]
As `instance.seek` currently is not capable of handling player instances with infinite `iteration-count` for `v0.1.3` `animation-iteration-count` is expected to yield undefined behavior. Compatibility this will land with the changes related to https://github.com/marionebl/jogwheel/issues/78

**Comment by KingHenne** [comment]
Sounds good.
